// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEEScsh-cmtYtq0vr1ZUeH04ZZv9-a4j4',
    appId: '1:620564251125:web:48ce23cb385c87e44760bc',
    messagingSenderId: '620564251125',
    projectId: 'insights-9a19d',
    authDomain: 'insights-9a19d.firebaseapp.com',
    storageBucket: 'insights-9a19d.firebasestorage.app',
    measurementId: 'G-1NRVRBSE05',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBMSXeZLIdEZZ5j13xv6yQqr3EgCljG5w',
    appId: '1:620564251125:android:f05b0cf348d39dc24760bc',
    messagingSenderId: '620564251125',
    projectId: 'insights-9a19d',
    storageBucket: 'insights-9a19d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASqC28083rg5D7TBgqWLX20TMRrC77FiI',
    appId: '1:620564251125:ios:e3a04917b1da88374760bc',
    messagingSenderId: '620564251125',
    projectId: 'insights-9a19d',
    storageBucket: 'insights-9a19d.firebasestorage.app',
    iosBundleId: 'com.insights.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASqC28083rg5D7TBgqWLX20TMRrC77FiI',
    appId: '1:620564251125:ios:e3a04917b1da88374760bc',
    messagingSenderId: '620564251125',
    projectId: 'insights-9a19d',
    storageBucket: 'insights-9a19d.firebasestorage.app',
    iosBundleId: 'com.insights.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAEEScsh-cmtYtq0vr1ZUeH04ZZv9-a4j4',
    appId: '1:620564251125:web:213d279ef2ca840e4760bc',
    messagingSenderId: '620564251125',
    projectId: 'insights-9a19d',
    authDomain: 'insights-9a19d.firebaseapp.com',
    storageBucket: 'insights-9a19d.firebasestorage.app',
    measurementId: 'G-3F7SZNJGGS',
  );
}
